GET http://localhost:3000/users

### userID at the end

GET http://localhost:3000/users/one
Content-Type: application/json

{
    "Token": "$2b$10$1GqkFGxhW.V1CooPdT92A.xDFrs8lKs8ITeQV5DrMycn2YPDwvNQW"
}

### 

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "UserName":"James",
    "Password":"Password",
    "Email":"User@email.com"
}

### userID at the end

DELETE http://localhost:3000/users/67094527007288bcf09dba51

### userID at the end

PATCH http://localhost:3000/users/
Content-Type: application/json

{
    "UserName": "Jack"
}

###

POST  http://localhost:3000/users/signin
Content-Type: application/json

{
    "UorE": "James",
    "Password": "Password"
}